# Generated by Django 3.0.8 on 2020-07-23 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='Identifier')),
                ('name', models.CharField(max_length=55, validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(55)], verbose_name='Name')),
                ('value', models.FloatField(validators=[django.core.validators.MinLengthValidator(0), django.core.validators.MaxLengthValidator(99999.9)], verbose_name='Value')),
                ('discount_value', models.FloatField(blank=True, null=True, verbose_name='Value')),
                ('stock', models.PositiveIntegerField(verbose_name='Stock')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
