# Generated by Django 3.0.8 on 2020-07-23 21:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200723_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='value',
            field=models.FloatField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(99999.8)], verbose_name='Value'),
        ),
    ]
