# Generated by Django 3.0.8 on 2020-07-24 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200724_0103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discount_value',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Discount Value'),
        ),
    ]
